import type { DatosFinanzas } from "@/dominio/tipos";

export const SEMILLA_FINANZAS_LOS_ALAMOS: DatosFinanzas = {
  fondoFijo: 5_000_000,
  movimientos: [
    {
      id: "mov-1",
      fecha: "2026-09-30",
      concepto: "Ferretería San Blas — hierro 12mm diámetro",
      categoria: "MATERIALES",
      fuente: "CUENTA",
      metodo: "TRANSFERENCIA",
      responsable: "J. Duarte",
      monto: -4_850_000,
      estado: "APROBADO",
      ruc: "80012345-6",
      factura: "001-002-0004561",
      proveedor: "Ferretería San Blas",
    },
    {
      id: "mov-2",
      fecha: "2026-10-02",
      concepto: "Liquidación jornaleros — semana 40",
      categoria: "MANO_DE_OBRA",
      fuente: "CAJA_CHICA",
      metodo: "EFECTIVO",
      responsable: "Ing. R. Benítez",
      monto: -2_680_000,
      estado: "APROBADO",
    },
    {
      id: "mov-3",
      fecha: "2026-10-05",
      concepto: "Certificado N° 06 cobrado parcial",
      categoria: "INGRESOS",
      fuente: "CERTIFICADO",
      metodo: "TRANSFERENCIA",
      responsable: "Admin",
      monto: 58_400_000,
      estado: "APROBADO",
    },
    {
      id: "mov-4",
      fecha: "2026-10-07",
      concepto: "Alquiler y traslado de andamios",
      categoria: "MAQUINARIAS",
      fuente: "CAJA_CHICA",
      metodo: "CHEQUE",
      responsable: "J. Duarte",
      monto: -1_450_000,
      estado: "PENDIENTE",
      ruc: "80022333-4",
      factura: "001-001-0002230",
      proveedor: "Andamios JP SRL",
    },
  ],
  jornaleros: [
    {
      id: "j-1",
      nombre: "Ramón Insfrán",
      ci: "1.234.567",
      rol: "PUNTERO",
      oficio: "Albañilería",
      jornalDiario: 140_000,
      alta: "2026-02-16",
      activo: true,
    },
    {
      id: "j-2",
      nombre: "Carlos Vera",
      ci: "2.345.678",
      rol: "OFICIAL",
      oficio: "Carpintería",
      jornalDiario: 110_000,
      alta: "2026-02-16",
      activo: true,
    },
  ],
  jornadas: [
    { id: "jrn-1", jornaleroId: "j-1", fecha: "2026-10-06", horasNormales: 8, horasExtra: 1, pagada: false },
    { id: "jrn-2", jornaleroId: "j-2", fecha: "2026-10-06", horasNormales: 8, horasExtra: 0, pagada: false },
  ],
  liquidaciones: [
    {
      id: "liq-1",
      nombre: "Ramón Insfrán",
      ci: "1.234.567",
      oficio: "Albañilería",
      diasTrabajados: 5,
      horasOrdinarias: 40,
      horasExtra: 4,
      jornalDiario: 140_000,
      total: 770_000,
      estado: "PENDIENTE",
    },
    {
      id: "liq-2",
      nombre: "Carlos Vera",
      ci: "2.345.678",
      oficio: "Carpintería",
      diasTrabajados: 5,
      horasOrdinarias: 40,
      horasExtra: 0,
      jornalDiario: 110_000,
      total: 550_000,
      estado: "PAGADO",
    },
  ],
  subcontratos: [
    {
      id: "sub-1",
      empresa: "Electropar Ltda.",
      especialidad: "Instalaciones eléctricas",
      contratoNro: "CT-2026-011",
      montoContratado: 96_000_000,
      montoCertificado: 41_200_000,
      avance: 0.43,
      estado: "EN_EJECUCION",
    },
    {
      id: "sub-2",
      empresa: "Plomería Ríos SRL",
      especialidad: "Instalaciones sanitarias",
      contratoNro: "CT-2026-015",
      montoContratado: 54_000_000,
      montoCertificado: 18_300_000,
      avance: 0.34,
      estado: "EN_EJECUCION",
    },
  ],
  certificados: [
    { id: "cert-1", numero: 5, periodo: "Agosto 2026", monto: 42_000_000, montoCobrado: 42_000_000, estado: "COBRADO" },
    { id: "cert-2", numero: 6, periodo: "Septiembre 2026", monto: 58_400_000, montoCobrado: 45_000_000, estado: "PENDIENTE" },
  ],
};

export const SEMILLA_FINANZAS: DatosFinanzas = SEMILLA_FINANZAS_LOS_ALAMOS;